package com.ligaya.designsystem

import androidx.compose.ui.graphics.Color

/**
 * Every colour a screen draws with, in one place, so the same screen can be painted light or dark.
 *
 * [LigayaColors] stays the light palette's definition and the source of these values — this type exists because an
 * object's properties cannot change with the theme. Screens read [LigayaTheme.colors]; the only reason to reach for
 * [LigayaColors] directly is a value needed outside a composable, such as a default parameter.
 */
data class LigayaPalette(
    val blush: Color,
    val blushDeep: Color,
    val rose: Color,
    val petal: Color,
    val petalDeep: Color,
    val roseDeep: Color,
    val onRoseDeep: Color,
    val canvas: Color,
    val surface: Color,
    val ink: Color,
    val inkSoft: Color,
    val cream: Color,
    val waveLight: Color,
    val waveDeep: Color,
    val cocoa: Color,
    val onCocoa: Color,
    val cocoaInk: Color,
    val taupe: Color,
    val creamDeep: Color,
    val shell: Color,
    val shellEdge: Color,
    val berry: Color,
    val onBerry: Color,
    val doodle: Color,
    val bubbleLigaya: Color,
    val bubbleLigayaEdge: Color,
    val bubbleUser: Color,
    val online: Color,
    val waveBar: Color,
    val listeningDisc: Color,
    val thoughtBubble: Color,
    val thinkingDot: Color,
    val thinkingDotLight: Color,
    val troubleDisc: Color,
    val confirmDisc: Color,
    val sparkle: Color,
    val onSurface: Color,
    val idleBackground: Color,
    val idlePrimary: Color,
    val onIdlePrimary: Color,
    val colorEmergencyActive: Color,
    val onEmergencyActive: Color,
    val emergencyBackground: Color,
    val resolved: Color,
    val onResolved: Color,
    val resolvedBackground: Color,
    val colorStatusPending: Color,
    val onStatusPending: Color,
    val colorStatusConfirmed: Color,
    val onStatusConfirmed: Color,
    val colorStatusFailed: Color,
    val onStatusFailed: Color,
)

/** The palette the app has always shipped, unchanged — see [LigayaColors] for what each token means. */
val LigayaLightPalette = LigayaPalette(
    blush = Color(0xFFF7EBE8),
    blushDeep = Color(0xFFF0DAD6),
    rose = Color(0xFFC48B8B),
    petal = Color(0xFFD5A68D),
    petalDeep = Color(0xFFC38E76),
    roseDeep = Color(0xFF9C5F66),
    onRoseDeep = Color(0xFFFFFFFF),
    canvas = Color(0xFFFAF7F6),
    surface = Color(0xFFFFFFFF),
    ink = Color(0xFF2E2A2B),
    inkSoft = Color(0xFF756A6C),
    cream = Color(0xFFFBF6F1),
    waveLight = Color(0xFFF8EDE6),
    waveDeep = Color(0xFFF3E1D7),
    cocoa = Color(0xFF4A2E2F),
    onCocoa = Color(0xFFFFFFFF),
    cocoaInk = Color(0xFF2E1F1D),
    taupe = Color(0xFF6E5E59),
    creamDeep = Color(0xFFF7ECE6),
    shell = Color(0xFFFFFCFA),
    shellEdge = Color(0xFFF0E4DE),
    berry = Color(0xFF8E3B46),
    onBerry = Color(0xFFFFFFFF),
    doodle = Color(0xFFB9777D),
    bubbleLigaya = Color(0xFFF7F1ED),
    bubbleLigayaEdge = Color(0xFFEDE3DD),
    bubbleUser = Color(0xFFF9E3E1),
    online = Color(0xFF3F9A66),
    waveBar = Color(0xFFD5A29E),
    listeningDisc = Color(0xFFFCF8F4),
    thoughtBubble = Color(0xFFC9AAA3),
    thinkingDot = Color(0xFF4F2226),
    thinkingDotLight = Color(0xFFEBCBBF),
    troubleDisc = Color(0xFFB95667),
    confirmDisc = Color(0xFF8AAF9B),
    sparkle = Color(0xFFE9C0A2),
    onSurface = Color(0xFF1B1F24),
    idleBackground = Color(0xFFF5F6F8),
    idlePrimary = Color(0xFF3A6EA5),
    onIdlePrimary = Color(0xFFFFFFFF),
    colorEmergencyActive = Color(0xFFC62828),
    onEmergencyActive = Color(0xFFFFFFFF),
    emergencyBackground = Color(0xFFFFF5F5),
    resolved = Color(0xFF2E7D32),
    onResolved = Color(0xFFFFFFFF),
    resolvedBackground = Color(0xFFF1F8F2),
    colorStatusPending = Color(0xFFF9A825),
    onStatusPending = Color(0xFF1B1F24),
    colorStatusConfirmed = Color(0xFF2E7D32),
    onStatusConfirmed = Color(0xFFFFFFFF),
    colorStatusFailed = Color(0xFFC62828),
    onStatusFailed = Color(0xFFFFFFFF),
)

/**
 * The same design at night, taken from the reference's dark Home: a near-black neutral page (#1E1F23), raised
 * surfaces a step lighter (#2C2E32 with #3C3E42 edges), near-white text and muted grey secondary text.
 *
 * The accents deliberately do not change. Berry, rose, the flower's petals, the status colours and the small
 * ornaments carry perfectly well on a dark page, and the reference draws them identically in both themes — her mic
 * button and her logo look the same at night. Only surfaces, text, and the washes behind them flip.
 */
val LigayaDarkPalette = LigayaPalette(
    blush = Color(0xFF24262A),
    blushDeep = Color(0xFF2A2C30),
    rose = Color(0xFFC48B8B),
    petal = Color(0xFFD5A68D),
    petalDeep = Color(0xFFC38E76),
    roseDeep = Color(0xFF9C5F66),
    onRoseDeep = Color(0xFFFFFFFF),
    canvas = Color(0xFF1E1F23),
    surface = Color(0xFF2C2E32),
    ink = Color(0xFFF5F1EB),
    inkSoft = Color(0xFFAEB0B5),
    cream = Color(0xFF1E1F23),
    waveLight = Color(0xFF232428),
    waveDeep = Color(0xFF2A2B30),
    cocoa = Color(0xFFF0ECE6),
    onCocoa = Color(0xFF1E1F23),
    cocoaInk = Color(0xFFF5F1EB),
    taupe = Color(0xFFAEB0B5),
    creamDeep = Color(0xFF17181C),
    shell = Color(0xFF2C2E32),
    shellEdge = Color(0xFF3C3E42),
    berry = Color(0xFF8E3B46),
    onBerry = Color(0xFFFFFFFF),
    doodle = Color(0xFFB9777D),
    bubbleLigaya = Color(0xFF2C2E32),
    bubbleLigayaEdge = Color(0xFF3C3E42),
    bubbleUser = Color(0xFF3B2B2F),
    online = Color(0xFF3F9A66),
    waveBar = Color(0xFFD5A29E),
    listeningDisc = Color(0xFF26272B),
    thoughtBubble = Color(0xFFC9AAA3),
    thinkingDot = Color(0xFFEAD5CF),
    thinkingDotLight = Color(0xFF7A5A56),
    troubleDisc = Color(0xFFB95667),
    confirmDisc = Color(0xFF8AAF9B),
    sparkle = Color(0xFFE9C0A2),
    onSurface = Color(0xFFF5F1EB),
    idleBackground = Color(0xFF1E1F23),
    idlePrimary = Color(0xFF3A6EA5),
    onIdlePrimary = Color(0xFFFFFFFF),
    colorEmergencyActive = Color(0xFFC62828),
    onEmergencyActive = Color(0xFFFFFFFF),
    emergencyBackground = Color(0xFF2A1A1A),
    resolved = Color(0xFF2E7D32),
    onResolved = Color(0xFFFFFFFF),
    resolvedBackground = Color(0xFF16211A),
    colorStatusPending = Color(0xFFF9A825),
    onStatusPending = Color(0xFFF5F1EB),
    colorStatusConfirmed = Color(0xFF2E7D32),
    onStatusConfirmed = Color(0xFFFFFFFF),
    colorStatusFailed = Color(0xFFC62828),
    onStatusFailed = Color(0xFFFFFFFF),
)
